sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t gimmizz/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true gimmizz/docker-react-app npm run test -- --coverage 
  # -e CI=true : CI에서 실행할 것임을 명시, 없으면 오류가 난다.
  # npm run test : 우리는 테스트를 수행할 것이니까, 명령어를 써야 한다.
  # coverage : 더 자세한 출력을 위함

after_success:
  - echo "Test success"

deploy:
  provider: elasticbeanstalk  # 외부 서비스 표시 (s3, elasticbeanstalk, firebase 등)
  region: "us-east-1"         # AWS region
  app: "docker-react-app"     # 생성된 어플리케이션의 이름
  env: "Dockerreactapp-env"   # 환경 이름. elasticbeanstalk에 보인다!
  bucket_name: "elasticbeanstalk-us-east-1-229001884462"  # S3 버킷 이름(elasticbeanstalk 생성 시, 자동생성)
  bucket_path: "docker-react-app"     # 어플리케이션 이름과 동일
  on:
    branch: main              # 어떤 브랜치에 push할 때 AWS에 배포할 것인지?
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY